# Generated by Django 2.1 on 2019-06-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(help_text='Device id', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('read_pipe', models.CharField(default='0xc2c2c2c2c2', help_text='Read pipe for device', max_length=1000)),
                ('write_pipe', models.CharField(default='0xe7e7e7e7e7', help_text='Write pipe for device', max_length=1000)),
            ],
        ),
    ]
