# Generated by Django 2.1 on 2019-06-07 12:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('time_off', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('total_time', models.DurationField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
