# Generated by Django 2.1 on 2019-06-07 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20190607_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineusage',
            name='device',
            field=models.ManyToManyField(to='basic_app.Device'),
        ),
        migrations.AlterField(
            model_name='machineusage',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
