# Generated by Django 2.1 on 2019-06-07 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0005_auto_20190607_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineusage',
            name='device',
        ),
        migrations.AddField(
            model_name='machineusage',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_app.Device'),
        ),
        migrations.RemoveField(
            model_name='machineusage',
            name='user',
        ),
        migrations.AddField(
            model_name='machineusage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
