# Generated by Django 2.2.4 on 2019-09-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_googlesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheet',
            name='credentials',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
