# Generated by Django 2.2.4 on 2019-09-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20190901_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheet',
            name='credentials',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
