# Generated by Django 2.1 on 2019-06-07 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_machineusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineusage',
            name='device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_app.Device'),
        ),
    ]
