# Generated by Django 2.1 on 2019-06-07 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0003_auto_20190607_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineusage',
            name='device',
        ),
        migrations.AddField(
            model_name='machineusage',
            name='device',
            field=models.ManyToManyField(null=True, to='basic_app.Device'),
        ),
        migrations.RemoveField(
            model_name='machineusage',
            name='user',
        ),
        migrations.AddField(
            model_name='machineusage',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
